apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: springio
  labels:
    app: mysql
type: Opaque
# Opaque:Unstructured, key-value pairs
data:
  #echo -n 'root' | base64
  # Decode:root
  root-password: cm9vdA==
  # Decode:admin
  user-name: YWRtaW4=
  # Decode:admin
  user-password: YWRtaW4=
