apiVersion: v1
kind: PersistentVolume    
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
    # Allows multiple pods which on the same node to access the volume. Can be read & write.
  hostPath:         
    path: /tmp