apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: springio-demo
  name: springio-demo
  namespace: springio
spec:
  replicas: 2
  # two replications
  selector:
    matchLabels:
      app: springio-demo
  template:
    metadata:
      labels:
        app: springio-demo
    spec:
      containers:
      - image: sunyayang/springio-demo:1.0.0
        # docker hub username / repository
        name: springio-demo
        ports:
            - containerPort: 8080
        imagePullPolicy: Always
        #Always : Means always pull image if the local cache doesn't exist. Otherwise Kube will use cached image.
        #https://kubernetes.io/docs/concepts/containers/images/#updating-images
